# -*- coding: utf-8 -*-
"""mathematical_functions_using_ttl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17GIc8dIDQG-kR3r4R2nh59tEoriIn2EW

# Sine Function Implementation using Test-Time Learning
"""

import torch
import torch.nn as nn
import matplotlib.pyplot as plt

class SineMLP(nn.Module):
    def __init__(self, dim=64):
        super().__init__()
        self.layer1 = nn.Linear(1, dim)
        self.layer2 = nn.Linear(dim, dim)
        self.layer3 = nn.Linear(dim, 1)
    def forward(self, x):
        x = torch.tanh(self.layer1(x))
        x = torch.tanh(self.layer2(x))
        x = self.layer3(x)
        return x

x_train = torch.linspace(-3, 3, 500).unsqueeze(1) # unsqueeze turns a flat list to a column of approptaite size
y_train = torch.sin(x_train)  + 0.05*torch.randn_like(x_train)

x_test = torch.linspace(3, 9, 500).unsqueeze(1)
y_test = torch.sin(x_test)

model = SineMLP()
y_pred = model(x_train)

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
plt.plot(x_train.numpy(), y_train.numpy(), label='train', markersize=8,)
plt.plot(x_test.numpy(), y_test.numpy(), label='test', markersize=8)
plt.xlabel('Input Params')
plt.ylabel('Output Params')
plt.title('Sine Wave')
plt.grid()
plt.legend()
plt.show()

def pretrain(model, x_train, y_train, epochs=1000, lr=0.01):
    optimizer = torch.optim.Adam(model.parameters(), lr=0.1)
    loss_fn = nn.MSELoss()
    for epoch in range(epochs):
        y_pred = model(x_train)
        loss = loss_fn(y_pred, y_train)
        optimizer.zero_grad() # clear old gradients
        loss.backward() # backprop
        optimizer.step() # update weights automatically
        if epoch % 10 == 0:
            print(f'Epoch {epoch}, Loss: {loss.item()}')
    return model

pretrain(model, x_train, y_train)

def evaluate(model, x_test, y_test):
    ...
model.eval()
with torch.no_grad():
    y_train_pred = model(x_train)
    y_test_pred = model(x_test)
plt.figure(figsize=(10, 5))
plt.plot(x_test.numpy(), y_test_pred.numpy(), label='test-pred', markersize=8)
plt.plot(x_test.numpy(), y_test.numpy(), label='test-true', markersize=8, alpha=0.3)
plt.plot(x_train.numpy(), y_train.numpy(), label='train-true', markersize=8, alpha=0.3)
plt.plot(x_train.numpy(), y_train_pred.numpy(), label='train-pred', markersize=100)
plt.legend()
plt.grid()
plt.show()

class LoRALinear(nn.Module):
    def __init__(self, base_linear: nn.Linear, rank=4):
        super().__init__()
        self.base = base_linear
        for p in self.base.parameters():
            p.requires_grad = False
        in_features = base_linear.in_features
        out_features = base_linear.out_features
        self.A = nn.Parameter(torch.randn(rank, in_features) * 0.01)
        print(self.A)
        self.B = nn.Parameter(torch.zeros(out_features, rank))
        print(self.B)

    def forward(self, x):
        base_out = self.base(x)
        lora_out = x @ self.A.T @ self.B.T
        return base_out + lora_out

if not isinstance(model.layer3, LoRALinear):
    lora_layer = LoRALinear(model.layer3, rank=4)
    model.layer3 = lora_layer
else:
    print("model.layer3 is already a LoRALinear layer. Skipping LoRA application.")

test_input = torch.randn(5, model.layer3.base.in_features)
out = lora_layer(test_input)
print(out.shape)  # should match (5, out_features)

base_only_out = lora_layer.base(test_input)
print(torch.allclose(out, base_only_out))  # should print True, since B starts at zero

def inject_lora(model: SineMLP, rank=4) -> SineMLP:
    for p in model.parameters():
        p.requires_grad = False
    model.layer3 = LoRALinear(model.layer3, rank=rank)
    return model

model = SineMLP()
pretrain(model, x_train, y_train, epochs=2000, lr=0.01)  # train normally first
model = inject_lora(model, rank=4)                        # now add LoRA

for name, p in model.named_parameters():
    print(name, p.requires_grad)

"""***something's to be debugged below***"""

def selection_score(model, x_train, n_perturb=5, eps=0.05):
    predictions = []
    with torch.no_grad():
        for _ in range(n_perturb):
            noise = torch.randn_like(x_train) * eps
            perturbed_input = x_train + noise
            perturbed_output = model(perturbed_input)
            predictions.append(perturbed_output)
    predictions = torch.stack(predictions)
    variance = predictions.var(dim=0)
    scores = -variance.squeeze()
    return scores

selection_score(model, x_test, 5, 0.05)

selection_score(model, x_train, 5, 0.05)

def select_top_k(x_batch, scores, k=7):
    top_k_indices = torch.topk(scores, k).indices
    x_selected = x_batch[top_k_indices]
    return x_selected

# x_batch = torch.linspace(3, 5, 20).unsqueeze(1)
scores = selection_score(model, x_train)
x_sel = select_top_k(x_train, scores, k=5)
print(x_sel.shape)
print(x_sel)

def consistency_loss(model, x_selected, n_perturb=5, eps=0.05):
    predictions = []

    for _ in range(n_perturb):
        noise = torch.randn_like(x_selected) * eps
        perturbed_input = x_selected + noise
        perturbed_output = model(perturbed_input)
        predictions.append(perturbed_output)

    predictions = torch.stack(predictions)
    variance = predictions.var(dim=0)

    loss = variance.mean()
    return loss

def test_time_adapt_and_predict(model_with_lora, test_x, batch_size, k_select, lora_lr):
    lora_params = [p for p in model_with_lora.parameters() if p.requires_grad]
    optimizer = torch.optim.SGD(lora_params, lr=lora_lr)

    all_predictions = []

    for batch_start in range(0, len(test_x), batch_size):
        x_batch = test_x[batch_start : batch_start + batch_size]

        # Step 4: predict (before this batch's update)
        with torch.no_grad():
            y_pred = model_with_lora(x_batch)

        # Step 5: score + select
        scores = selection_score(model_with_lora, x_batch)
        x_selected = select_top_k(x_batch, scores, k_select)

        # Step 6: update LoRA params
        optimizer.zero_grad()
        loss = consistency_loss(model_with_lora, x_selected)
        loss.backward()
        optimizer.step()

        all_predictions.append(y_pred)

    return torch.cat(all_predictions)

import matplotlib.pyplot as plt

def plot_results(x_train, y_train, x_test, y_test_true, y_pred):
    plt.figure(figsize=(10, 6))

    plt.plot(x_train, y_train, color='gray', alpha=0.4, label='train (noisy)')
    plt.plot(x_test, y_test_true, color='black', linewidth=2, label='test (true sine)')
    plt.plot(x_test, y_pred.detach(), color='green', label='TTL-adapted')

    plt.axvline(x=x_train[-1].item(), color='blue', linestyle=':', alpha=0.5, label='train/test boundary')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.title('Sine Extrapolation: Baseline vs Test-Time Learning')
    plt.legend()
    plt.grid(True)
    plt.show()

y_ttl = test_time_adapt_and_predict(model, x_test, batch_size=50, k_select=10, lora_lr=1e-2)
plot_results(x_train, y_train, x_test, y_test, y_ttl)

"""<div></div>

# Linear Function Implementation using Test-Time Learning
"""

SLOPE = 2.0
INTERCEPT = 1.0

def true_fn(x):
    return SLOPE * x + INTERCEPT

class LinearMLP(nn.Module):
    def __init__(self, dim=64):
        super().__init__()
        self.layer1 = nn.Linear(1, dim)
        self.layer2 = nn.Linear(dim, dim)
        self.layer3 = nn.Linear(dim, 1)

    def forward(self, x):
        x = torch.tanh(self.layer1(x))
        x = torch.tanh(self.layer2(x))
        x = self.layer3(x)
        return x

x_train = torch.linspace(-3, 3, 500).unsqueeze(1)
y_train = true_fn(x_train) + 0.05 * torch.randn_like(x_train)

x_test = torch.linspace(4, 7, 500).unsqueeze(1)
y_test = true_fn(x_test)

def pretrain(model, x, y, epochs=2000, lr=1e-2):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.MSELoss()
    for epoch in range(epochs):
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if epoch % 200 == 0:
            print(f'Epoch {epoch}, Loss: {loss.item()}')
    return model

def evaluate(model, x, y):
    model.eval()
    with torch.no_grad():
        return nn.functional.mse_loss(model(x), y).item()

class LoRALinear(nn.Module):
    def __init__(self, base_linear: nn.Linear, rank=4):
        super().__init__()
        self.base = base_linear
        for p in self.base.parameters():
            p.requires_grad = False
        self.A = nn.Parameter(torch.randn(rank, base_linear.in_features) * 0.01)
        self.B = nn.Parameter(torch.zeros(base_linear.out_features, rank))

    def forward(self, x):
        return self.base(x) + x @ self.A.T @ self.B.T


def inject_lora(model, rank=4):
    for p in model.parameters():
        p.requires_grad = False
    model.layer1 = LoRALinear(model.layer1, rank)
    model.layer2 = LoRALinear(model.layer2, rank)
    model.layer3 = LoRALinear(model.layer3, rank)
    return model

def selection_score(model, x, n_perturb=5, eps=0.05):
    preds = []
    with torch.no_grad():
        for _ in range(n_perturb):
            preds.append(model(x + torch.randn_like(x) * eps))
    return torch.stack(preds).var(dim=0).squeeze(-1)


def select_top_k(x_batch, scores, k=7):
    k = min(k, len(x_batch))
    return x_batch[torch.topk(scores, k).indices]


def linear_residual_loss(model, x):
    """Label-free prior: a line has zero curvature, y'' = 0."""
    x = x.clone().requires_grad_(True)
    y = model(x)
    dy = torch.autograd.grad(y.sum(), x, create_graph=True)[0]
    d2y = torch.autograd.grad(dy.sum(), x, create_graph=True)[0]
    return (d2y ** 2).mean()


def test_time_adapt_and_predict(
    model, test_x, batch_size=50, k_select=None, lora_lr=1e-2, n_steps=30,
    anchor=None, anchor_weight=1.0, predict_before_update=False,
):
    """y''=0 allows ANY line, so `anchor` (source-data replay) is what pins
    slope and intercept. anchor=None gives the pure, label-free version."""
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = torch.optim.Adam(params, lr=lora_lr)
    all_preds = []

    for start in range(0, len(test_x), batch_size):
        xb = test_x[start:start + batch_size]

        if predict_before_update:
            with torch.no_grad():
                all_preds.append(model(xb))

        xs = xb
        if k_select is not None:
            xs = select_top_k(xb, selection_score(model, xb), k_select)

        for _ in range(n_steps):
            optimizer.zero_grad()
            loss = linear_residual_loss(model, xs)
            if anchor is not None:
                ax, ay = anchor
                loss = loss + anchor_weight * nn.functional.mse_loss(model(ax), ay)
            loss.backward()
            optimizer.step()

        if not predict_before_update:
            with torch.no_grad():
                all_preds.append(model(xb))

    return torch.cat(all_preds)

def plot_results(x_train, y_train, x_test, y_test_true, y_base, y_ttl):
    plt.figure(figsize=(10, 6))
    plt.plot(x_train, y_train, color="gray", alpha=0.4, label="train (noisy)")
    plt.plot(x_test, y_test_true, color="black", linewidth=2, label="test (true line)")
    plt.plot(x_test, y_base, color="red", linestyle="--", label="baseline (no TTL)")
    plt.plot(x_test, y_ttl, color="green", label="TTL-adapted")
    plt.axvline(x=x_train[-1].item(), color="blue", linestyle=":", alpha=0.5,
                label="train/test boundary")
    plt.xlabel("x"); plt.ylabel("y")
    plt.title(f"Linear extrapolation (y = {SLOPE}x + {INTERCEPT}): baseline vs TTL")
    plt.legend(); plt.grid(True); plt.show()

if __name__ == "__main__":
    base = LinearMLP()
    pretrain(base, x_train, y_train, epochs=2000, lr=1e-2)
    base.eval()
    with torch.no_grad():
        y_base = base(x_test)
    print("Baseline Test MSE:", evaluate(base, x_test, y_test))

    base_copy = copy.deepcopy(base)
    ttl_model = inject_lora(base_copy, rank=7)
    with torch.no_grad():
        assert torch.allclose(ttl_model(x_test), y_base)

    y_ttl = test_time_adapt_and_predict(ttl_model, x_test, batch_size=50, k_select=10, lora_lr=1e-2, n_steps=50)

    print("TTL test MSE:", nn.functional.mse_loss(y_ttl, y_test).item())

    plot_results(x_train, y_train, x_test, y_test, y_base, y_ttl)

